[theme]
base = "dark"
primaryColor = "#0099ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
